# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/emjay/Documents/school/2_ING/DP/coding/BlockEditor2_mmcontext

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/emjay/Documents/school/2_ING/DP/coding/BlockEditor2_mmcontext

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Data\" \"Runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emjay/Documents/school/2_ING/DP/coding/BlockEditor2_mmcontext/CMakeFiles /home/emjay/Documents/school/2_ING/DP/coding/BlockEditor2_mmcontext/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emjay/Documents/school/2_ING/DP/coding/BlockEditor2_mmcontext/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BlockEditor

# Build rule for target.
BlockEditor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockEditor
.PHONY : BlockEditor

# fast build rule for target.
BlockEditor/fast:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/build
.PHONY : BlockEditor/fast

#=============================================================================
# Target rules for targets named BlockEditor_automoc

# Build rule for target.
BlockEditor_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockEditor_automoc
.PHONY : BlockEditor_automoc

# fast build rule for target.
BlockEditor_automoc/fast:
	$(MAKE) -f CMakeFiles/BlockEditor_automoc.dir/build.make CMakeFiles/BlockEditor_automoc.dir/build
.PHONY : BlockEditor_automoc/fast

#=============================================================================
# Target rules for targets named BlockEditor_pch

# Build rule for target.
BlockEditor_pch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockEditor_pch
.PHONY : BlockEditor_pch

# fast build rule for target.
BlockEditor_pch/fast:
	$(MAKE) -f CMakeFiles/BlockEditor_pch.dir/build.make CMakeFiles/BlockEditor_pch.dir/build
.PHONY : BlockEditor_pch/fast

#=============================================================================
# Target rules for targets named BlockEditor_unity

# Build rule for target.
BlockEditor_unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockEditor_unity
.PHONY : BlockEditor_unity

# fast build rule for target.
BlockEditor_unity/fast:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/build
.PHONY : BlockEditor_unity/fast

#=============================================================================
# Target rules for targets named BlockEditor_unity_automoc

# Build rule for target.
BlockEditor_unity_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockEditor_unity_automoc
.PHONY : BlockEditor_unity_automoc

# fast build rule for target.
BlockEditor_unity_automoc/fast:
	$(MAKE) -f CMakeFiles/BlockEditor_unity_automoc.dir/build.make CMakeFiles/BlockEditor_unity_automoc.dir/build
.PHONY : BlockEditor_unity_automoc/fast

#=============================================================================
# Target rules for targets named all_pch

# Build rule for target.
all_pch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_pch
.PHONY : all_pch

# fast build rule for target.
all_pch/fast:
	$(MAKE) -f CMakeFiles/all_pch.dir/build.make CMakeFiles/all_pch.dir/build
.PHONY : all_pch/fast

#=============================================================================
# Target rules for targets named all_unity

# Build rule for target.
all_unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_unity
.PHONY : all_unity

# fast build rule for target.
all_unity/fast:
	$(MAKE) -f CMakeFiles/all_unity.dir/build.make CMakeFiles/all_unity.dir/build
.PHONY : all_unity/fast

#=============================================================================
# Target rules for targets named clean_cotire

# Build rule for target.
clean_cotire: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_cotire
.PHONY : clean_cotire

# fast build rule for target.
clean_cotire/fast:
	$(MAKE) -f CMakeFiles/clean_cotire.dir/build.make CMakeFiles/clean_cotire.dir/build
.PHONY : clean_cotire/fast

#=============================================================================
# Target rules for targets named install_unity

# Build rule for target.
install_unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 install_unity
.PHONY : install_unity

# fast build rule for target.
install_unity/fast:
	$(MAKE) -f CMakeFiles/install_unity.dir/build.make CMakeFiles/install_unity.dir/build
.PHONY : install_unity/fast

BlockEditor_automoc.o: BlockEditor_automoc.cpp.o

.PHONY : BlockEditor_automoc.o

# target to build an object file
BlockEditor_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/BlockEditor_automoc.cpp.o
.PHONY : BlockEditor_automoc.cpp.o

BlockEditor_automoc.i: BlockEditor_automoc.cpp.i

.PHONY : BlockEditor_automoc.i

# target to preprocess a source file
BlockEditor_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/BlockEditor_automoc.cpp.i
.PHONY : BlockEditor_automoc.cpp.i

BlockEditor_automoc.s: BlockEditor_automoc.cpp.s

.PHONY : BlockEditor_automoc.s

# target to generate assembly for a file
BlockEditor_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/BlockEditor_automoc.cpp.s
.PHONY : BlockEditor_automoc.cpp.s

BlockEditor_unity_automoc.o: BlockEditor_unity_automoc.cpp.o

.PHONY : BlockEditor_unity_automoc.o

# target to build an object file
BlockEditor_unity_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/BlockEditor_unity_automoc.cpp.o
.PHONY : BlockEditor_unity_automoc.cpp.o

BlockEditor_unity_automoc.i: BlockEditor_unity_automoc.cpp.i

.PHONY : BlockEditor_unity_automoc.i

# target to preprocess a source file
BlockEditor_unity_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/BlockEditor_unity_automoc.cpp.i
.PHONY : BlockEditor_unity_automoc.cpp.i

BlockEditor_unity_automoc.s: BlockEditor_unity_automoc.cpp.s

.PHONY : BlockEditor_unity_automoc.s

# target to generate assembly for a file
BlockEditor_unity_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/BlockEditor_unity_automoc.cpp.s
.PHONY : BlockEditor_unity_automoc.cpp.s

cotire/BlockEditor_CXX_unity_0_13.o: cotire/BlockEditor_CXX_unity_0_13.cxx.o

.PHONY : cotire/BlockEditor_CXX_unity_0_13.o

# target to build an object file
cotire/BlockEditor_CXX_unity_0_13.cxx.o:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/cotire/BlockEditor_CXX_unity_0_13.cxx.o
.PHONY : cotire/BlockEditor_CXX_unity_0_13.cxx.o

cotire/BlockEditor_CXX_unity_0_13.i: cotire/BlockEditor_CXX_unity_0_13.cxx.i

.PHONY : cotire/BlockEditor_CXX_unity_0_13.i

# target to preprocess a source file
cotire/BlockEditor_CXX_unity_0_13.cxx.i:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/cotire/BlockEditor_CXX_unity_0_13.cxx.i
.PHONY : cotire/BlockEditor_CXX_unity_0_13.cxx.i

cotire/BlockEditor_CXX_unity_0_13.s: cotire/BlockEditor_CXX_unity_0_13.cxx.s

.PHONY : cotire/BlockEditor_CXX_unity_0_13.s

# target to generate assembly for a file
cotire/BlockEditor_CXX_unity_0_13.cxx.s:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/cotire/BlockEditor_CXX_unity_0_13.cxx.s
.PHONY : cotire/BlockEditor_CXX_unity_0_13.cxx.s

cotire/BlockEditor_CXX_unity_14_26.o: cotire/BlockEditor_CXX_unity_14_26.cxx.o

.PHONY : cotire/BlockEditor_CXX_unity_14_26.o

# target to build an object file
cotire/BlockEditor_CXX_unity_14_26.cxx.o:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/cotire/BlockEditor_CXX_unity_14_26.cxx.o
.PHONY : cotire/BlockEditor_CXX_unity_14_26.cxx.o

cotire/BlockEditor_CXX_unity_14_26.i: cotire/BlockEditor_CXX_unity_14_26.cxx.i

.PHONY : cotire/BlockEditor_CXX_unity_14_26.i

# target to preprocess a source file
cotire/BlockEditor_CXX_unity_14_26.cxx.i:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/cotire/BlockEditor_CXX_unity_14_26.cxx.i
.PHONY : cotire/BlockEditor_CXX_unity_14_26.cxx.i

cotire/BlockEditor_CXX_unity_14_26.s: cotire/BlockEditor_CXX_unity_14_26.cxx.s

.PHONY : cotire/BlockEditor_CXX_unity_14_26.s

# target to generate assembly for a file
cotire/BlockEditor_CXX_unity_14_26.cxx.s:
	$(MAKE) -f CMakeFiles/BlockEditor_unity.dir/build.make CMakeFiles/BlockEditor_unity.dir/cotire/BlockEditor_CXX_unity_14_26.cxx.s
.PHONY : cotire/BlockEditor_CXX_unity_14_26.cxx.s

src/highlighter.o: src/highlighter.cpp.o

.PHONY : src/highlighter.o

# target to build an object file
src/highlighter.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/highlighter.cpp.o
.PHONY : src/highlighter.cpp.o

src/highlighter.i: src/highlighter.cpp.i

.PHONY : src/highlighter.i

# target to preprocess a source file
src/highlighter.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/highlighter.cpp.i
.PHONY : src/highlighter.cpp.i

src/highlighter.s: src/highlighter.cpp.s

.PHONY : src/highlighter.s

# target to generate assembly for a file
src/highlighter.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/highlighter.cpp.s
.PHONY : src/highlighter.cpp.s

src/item/abstractelement.o: src/item/abstractelement.cpp.o

.PHONY : src/item/abstractelement.o

# target to build an object file
src/item/abstractelement.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/abstractelement.cpp.o
.PHONY : src/item/abstractelement.cpp.o

src/item/abstractelement.i: src/item/abstractelement.cpp.i

.PHONY : src/item/abstractelement.i

# target to preprocess a source file
src/item/abstractelement.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/abstractelement.cpp.i
.PHONY : src/item/abstractelement.cpp.i

src/item/abstractelement.s: src/item/abstractelement.cpp.s

.PHONY : src/item/abstractelement.s

# target to generate assembly for a file
src/item/abstractelement.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/abstractelement.cpp.s
.PHONY : src/item/abstractelement.cpp.s

src/item/blankItem.o: src/item/blankItem.cpp.o

.PHONY : src/item/blankItem.o

# target to build an object file
src/item/blankItem.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/blankItem.cpp.o
.PHONY : src/item/blankItem.cpp.o

src/item/blankItem.i: src/item/blankItem.cpp.i

.PHONY : src/item/blankItem.i

# target to preprocess a source file
src/item/blankItem.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/blankItem.cpp.i
.PHONY : src/item/blankItem.cpp.i

src/item/blankItem.s: src/item/blankItem.cpp.s

.PHONY : src/item/blankItem.s

# target to generate assembly for a file
src/item/blankItem.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/blankItem.cpp.s
.PHONY : src/item/blankItem.cpp.s

src/item/item.o: src/item/item.cpp.o

.PHONY : src/item/item.o

# target to build an object file
src/item/item.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/item.cpp.o
.PHONY : src/item/item.cpp.o

src/item/item.i: src/item/item.cpp.i

.PHONY : src/item/item.i

# target to preprocess a source file
src/item/item.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/item.cpp.i
.PHONY : src/item/item.cpp.i

src/item/item.s: src/item/item.cpp.s

.PHONY : src/item/item.s

# target to generate assembly for a file
src/item/item.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/item.cpp.s
.PHONY : src/item/item.cpp.s

src/item/layout.o: src/item/layout.cpp.o

.PHONY : src/item/layout.o

# target to build an object file
src/item/layout.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/layout.cpp.o
.PHONY : src/item/layout.cpp.o

src/item/layout.i: src/item/layout.cpp.i

.PHONY : src/item/layout.i

# target to preprocess a source file
src/item/layout.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/layout.cpp.i
.PHONY : src/item/layout.cpp.i

src/item/layout.s: src/item/layout.cpp.s

.PHONY : src/item/layout.s

# target to generate assembly for a file
src/item/layout.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/layout.cpp.s
.PHONY : src/item/layout.cpp.s

src/item/textitem.o: src/item/textitem.cpp.o

.PHONY : src/item/textitem.o

# target to build an object file
src/item/textitem.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/textitem.cpp.o
.PHONY : src/item/textitem.cpp.o

src/item/textitem.i: src/item/textitem.cpp.i

.PHONY : src/item/textitem.i

# target to preprocess a source file
src/item/textitem.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/textitem.cpp.i
.PHONY : src/item/textitem.cpp.i

src/item/textitem.s: src/item/textitem.cpp.s

.PHONY : src/item/textitem.s

# target to generate assembly for a file
src/item/textitem.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/item/textitem.cpp.s
.PHONY : src/item/textitem.cpp.s

src/lineeditor.o: src/lineeditor.cpp.o

.PHONY : src/lineeditor.o

# target to build an object file
src/lineeditor.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/lineeditor.cpp.o
.PHONY : src/lineeditor.cpp.o

src/lineeditor.i: src/lineeditor.cpp.i

.PHONY : src/lineeditor.i

# target to preprocess a source file
src/lineeditor.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/lineeditor.cpp.i
.PHONY : src/lineeditor.cpp.i

src/lineeditor.s: src/lineeditor.cpp.s

.PHONY : src/lineeditor.s

# target to generate assembly for a file
src/lineeditor.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/lineeditor.cpp.s
.PHONY : src/lineeditor.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainview.o: src/mainview.cpp.o

.PHONY : src/mainview.o

# target to build an object file
src/mainview.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/mainview.cpp.o
.PHONY : src/mainview.cpp.o

src/mainview.i: src/mainview.cpp.i

.PHONY : src/mainview.i

# target to preprocess a source file
src/mainview.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/mainview.cpp.i
.PHONY : src/mainview.cpp.i

src/mainview.s: src/mainview.cpp.s

.PHONY : src/mainview.s

# target to generate assembly for a file
src/mainview.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/mainview.cpp.s
.PHONY : src/mainview.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o

.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i

.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s

.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/minimapview.o: src/minimapview.cpp.o

.PHONY : src/minimapview.o

# target to build an object file
src/minimapview.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/minimapview.cpp.o
.PHONY : src/minimapview.cpp.o

src/minimapview.i: src/minimapview.cpp.i

.PHONY : src/minimapview.i

# target to preprocess a source file
src/minimapview.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/minimapview.cpp.i
.PHONY : src/minimapview.cpp.i

src/minimapview.s: src/minimapview.cpp.s

.PHONY : src/minimapview.s

# target to generate assembly for a file
src/minimapview.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/minimapview.cpp.s
.PHONY : src/minimapview.cpp.s

src/scene/blockscene.o: src/scene/blockscene.cpp.o

.PHONY : src/scene/blockscene.o

# target to build an object file
src/scene/blockscene.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/blockscene.cpp.o
.PHONY : src/scene/blockscene.cpp.o

src/scene/blockscene.i: src/scene/blockscene.cpp.i

.PHONY : src/scene/blockscene.i

# target to preprocess a source file
src/scene/blockscene.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/blockscene.cpp.i
.PHONY : src/scene/blockscene.cpp.i

src/scene/blockscene.s: src/scene/blockscene.cpp.s

.PHONY : src/scene/blockscene.s

# target to generate assembly for a file
src/scene/blockscene.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/blockscene.cpp.s
.PHONY : src/scene/blockscene.cpp.s

src/scene/command/changemarkedcommand.o: src/scene/command/changemarkedcommand.cpp.o

.PHONY : src/scene/command/changemarkedcommand.o

# target to build an object file
src/scene/command/changemarkedcommand.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/changemarkedcommand.cpp.o
.PHONY : src/scene/command/changemarkedcommand.cpp.o

src/scene/command/changemarkedcommand.i: src/scene/command/changemarkedcommand.cpp.i

.PHONY : src/scene/command/changemarkedcommand.i

# target to preprocess a source file
src/scene/command/changemarkedcommand.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/changemarkedcommand.cpp.i
.PHONY : src/scene/command/changemarkedcommand.cpp.i

src/scene/command/changemarkedcommand.s: src/scene/command/changemarkedcommand.cpp.s

.PHONY : src/scene/command/changemarkedcommand.s

# target to generate assembly for a file
src/scene/command/changemarkedcommand.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/changemarkedcommand.cpp.s
.PHONY : src/scene/command/changemarkedcommand.cpp.s

src/scene/command/command.o: src/scene/command/command.cpp.o

.PHONY : src/scene/command/command.o

# target to build an object file
src/scene/command/command.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/command.cpp.o
.PHONY : src/scene/command/command.cpp.o

src/scene/command/command.i: src/scene/command/command.cpp.i

.PHONY : src/scene/command/command.i

# target to preprocess a source file
src/scene/command/command.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/command.cpp.i
.PHONY : src/scene/command/command.cpp.i

src/scene/command/command.s: src/scene/command/command.cpp.s

.PHONY : src/scene/command/command.s

# target to generate assembly for a file
src/scene/command/command.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/command.cpp.s
.PHONY : src/scene/command/command.cpp.s

src/scene/command/cursormovecommand.o: src/scene/command/cursormovecommand.cpp.o

.PHONY : src/scene/command/cursormovecommand.o

# target to build an object file
src/scene/command/cursormovecommand.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/cursormovecommand.cpp.o
.PHONY : src/scene/command/cursormovecommand.cpp.o

src/scene/command/cursormovecommand.i: src/scene/command/cursormovecommand.cpp.i

.PHONY : src/scene/command/cursormovecommand.i

# target to preprocess a source file
src/scene/command/cursormovecommand.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/cursormovecommand.cpp.i
.PHONY : src/scene/command/cursormovecommand.cpp.i

src/scene/command/cursormovecommand.s: src/scene/command/cursormovecommand.cpp.s

.PHONY : src/scene/command/cursormovecommand.s

# target to generate assembly for a file
src/scene/command/cursormovecommand.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/cursormovecommand.cpp.s
.PHONY : src/scene/command/cursormovecommand.cpp.s

src/scene/command/dragelemententercommand.o: src/scene/command/dragelemententercommand.cpp.o

.PHONY : src/scene/command/dragelemententercommand.o

# target to build an object file
src/scene/command/dragelemententercommand.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/dragelemententercommand.cpp.o
.PHONY : src/scene/command/dragelemententercommand.cpp.o

src/scene/command/dragelemententercommand.i: src/scene/command/dragelemententercommand.cpp.i

.PHONY : src/scene/command/dragelemententercommand.i

# target to preprocess a source file
src/scene/command/dragelemententercommand.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/dragelemententercommand.cpp.i
.PHONY : src/scene/command/dragelemententercommand.cpp.i

src/scene/command/dragelemententercommand.s: src/scene/command/dragelemententercommand.cpp.s

.PHONY : src/scene/command/dragelemententercommand.s

# target to generate assembly for a file
src/scene/command/dragelemententercommand.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/dragelemententercommand.cpp.s
.PHONY : src/scene/command/dragelemententercommand.cpp.s

src/scene/command/dragelementleavecommand.o: src/scene/command/dragelementleavecommand.cpp.o

.PHONY : src/scene/command/dragelementleavecommand.o

# target to build an object file
src/scene/command/dragelementleavecommand.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/dragelementleavecommand.cpp.o
.PHONY : src/scene/command/dragelementleavecommand.cpp.o

src/scene/command/dragelementleavecommand.i: src/scene/command/dragelementleavecommand.cpp.i

.PHONY : src/scene/command/dragelementleavecommand.i

# target to preprocess a source file
src/scene/command/dragelementleavecommand.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/dragelementleavecommand.cpp.i
.PHONY : src/scene/command/dragelementleavecommand.cpp.i

src/scene/command/dragelementleavecommand.s: src/scene/command/dragelementleavecommand.cpp.s

.PHONY : src/scene/command/dragelementleavecommand.s

# target to generate assembly for a file
src/scene/command/dragelementleavecommand.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/dragelementleavecommand.cpp.s
.PHONY : src/scene/command/dragelementleavecommand.cpp.s

src/scene/command/dropelementcommand.o: src/scene/command/dropelementcommand.cpp.o

.PHONY : src/scene/command/dropelementcommand.o

# target to build an object file
src/scene/command/dropelementcommand.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/dropelementcommand.cpp.o
.PHONY : src/scene/command/dropelementcommand.cpp.o

src/scene/command/dropelementcommand.i: src/scene/command/dropelementcommand.cpp.i

.PHONY : src/scene/command/dropelementcommand.i

# target to preprocess a source file
src/scene/command/dropelementcommand.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/dropelementcommand.cpp.i
.PHONY : src/scene/command/dropelementcommand.cpp.i

src/scene/command/dropelementcommand.s: src/scene/command/dropelementcommand.cpp.s

.PHONY : src/scene/command/dropelementcommand.s

# target to generate assembly for a file
src/scene/command/dropelementcommand.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/dropelementcommand.cpp.s
.PHONY : src/scene/command/dropelementcommand.cpp.s

src/scene/command/moveelementcommand.o: src/scene/command/moveelementcommand.cpp.o

.PHONY : src/scene/command/moveelementcommand.o

# target to build an object file
src/scene/command/moveelementcommand.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/moveelementcommand.cpp.o
.PHONY : src/scene/command/moveelementcommand.cpp.o

src/scene/command/moveelementcommand.i: src/scene/command/moveelementcommand.cpp.i

.PHONY : src/scene/command/moveelementcommand.i

# target to preprocess a source file
src/scene/command/moveelementcommand.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/moveelementcommand.cpp.i
.PHONY : src/scene/command/moveelementcommand.cpp.i

src/scene/command/moveelementcommand.s: src/scene/command/moveelementcommand.cpp.s

.PHONY : src/scene/command/moveelementcommand.s

# target to generate assembly for a file
src/scene/command/moveelementcommand.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/moveelementcommand.cpp.s
.PHONY : src/scene/command/moveelementcommand.cpp.s

src/scene/command/selectitemcommand.o: src/scene/command/selectitemcommand.cpp.o

.PHONY : src/scene/command/selectitemcommand.o

# target to build an object file
src/scene/command/selectitemcommand.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/selectitemcommand.cpp.o
.PHONY : src/scene/command/selectitemcommand.cpp.o

src/scene/command/selectitemcommand.i: src/scene/command/selectitemcommand.cpp.i

.PHONY : src/scene/command/selectitemcommand.i

# target to preprocess a source file
src/scene/command/selectitemcommand.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/selectitemcommand.cpp.i
.PHONY : src/scene/command/selectitemcommand.cpp.i

src/scene/command/selectitemcommand.s: src/scene/command/selectitemcommand.cpp.s

.PHONY : src/scene/command/selectitemcommand.s

# target to generate assembly for a file
src/scene/command/selectitemcommand.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/command/selectitemcommand.cpp.s
.PHONY : src/scene/command/selectitemcommand.cpp.s

src/scene/linenumbers.o: src/scene/linenumbers.cpp.o

.PHONY : src/scene/linenumbers.o

# target to build an object file
src/scene/linenumbers.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/linenumbers.cpp.o
.PHONY : src/scene/linenumbers.cpp.o

src/scene/linenumbers.i: src/scene/linenumbers.cpp.i

.PHONY : src/scene/linenumbers.i

# target to preprocess a source file
src/scene/linenumbers.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/linenumbers.cpp.i
.PHONY : src/scene/linenumbers.cpp.i

src/scene/linenumbers.s: src/scene/linenumbers.cpp.s

.PHONY : src/scene/linenumbers.s

# target to generate assembly for a file
src/scene/linenumbers.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/linenumbers.cpp.s
.PHONY : src/scene/linenumbers.cpp.s

src/scene/mimedata.o: src/scene/mimedata.cpp.o

.PHONY : src/scene/mimedata.o

# target to build an object file
src/scene/mimedata.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/mimedata.cpp.o
.PHONY : src/scene/mimedata.cpp.o

src/scene/mimedata.i: src/scene/mimedata.cpp.i

.PHONY : src/scene/mimedata.i

# target to preprocess a source file
src/scene/mimedata.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/mimedata.cpp.i
.PHONY : src/scene/mimedata.cpp.i

src/scene/mimedata.s: src/scene/mimedata.cpp.s

.PHONY : src/scene/mimedata.s

# target to generate assembly for a file
src/scene/mimedata.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/mimedata.cpp.s
.PHONY : src/scene/mimedata.cpp.s

src/scene/parser.o: src/scene/parser.cpp.o

.PHONY : src/scene/parser.o

# target to build an object file
src/scene/parser.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/parser.cpp.o
.PHONY : src/scene/parser.cpp.o

src/scene/parser.i: src/scene/parser.cpp.i

.PHONY : src/scene/parser.i

# target to preprocess a source file
src/scene/parser.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/parser.cpp.i
.PHONY : src/scene/parser.cpp.i

src/scene/parser.s: src/scene/parser.cpp.s

.PHONY : src/scene/parser.s

# target to generate assembly for a file
src/scene/parser.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/parser.cpp.s
.PHONY : src/scene/parser.cpp.s

src/scene/sceneeventobserver.o: src/scene/sceneeventobserver.cpp.o

.PHONY : src/scene/sceneeventobserver.o

# target to build an object file
src/scene/sceneeventobserver.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/sceneeventobserver.cpp.o
.PHONY : src/scene/sceneeventobserver.cpp.o

src/scene/sceneeventobserver.i: src/scene/sceneeventobserver.cpp.i

.PHONY : src/scene/sceneeventobserver.i

# target to preprocess a source file
src/scene/sceneeventobserver.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/sceneeventobserver.cpp.i
.PHONY : src/scene/sceneeventobserver.cpp.i

src/scene/sceneeventobserver.s: src/scene/sceneeventobserver.cpp.s

.PHONY : src/scene/sceneeventobserver.s

# target to generate assembly for a file
src/scene/sceneeventobserver.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/sceneeventobserver.cpp.s
.PHONY : src/scene/sceneeventobserver.cpp.s

src/scene/scenestate.o: src/scene/scenestate.cpp.o

.PHONY : src/scene/scenestate.o

# target to build an object file
src/scene/scenestate.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/scenestate.cpp.o
.PHONY : src/scene/scenestate.cpp.o

src/scene/scenestate.i: src/scene/scenestate.cpp.i

.PHONY : src/scene/scenestate.i

# target to preprocess a source file
src/scene/scenestate.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/scenestate.cpp.i
.PHONY : src/scene/scenestate.cpp.i

src/scene/scenestate.s: src/scene/scenestate.cpp.s

.PHONY : src/scene/scenestate.s

# target to generate assembly for a file
src/scene/scenestate.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/scene/scenestate.cpp.s
.PHONY : src/scene/scenestate.cpp.s

src/style/style.o: src/style/style.cpp.o

.PHONY : src/style/style.o

# target to build an object file
src/style/style.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/style/style.cpp.o
.PHONY : src/style/style.cpp.o

src/style/style.i: src/style/style.cpp.i

.PHONY : src/style/style.i

# target to preprocess a source file
src/style/style.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/style/style.cpp.i
.PHONY : src/style/style.cpp.i

src/style/style.s: src/style/style.cpp.s

.PHONY : src/style/style.s

# target to generate assembly for a file
src/style/style.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/style/style.cpp.s
.PHONY : src/style/style.cpp.s

src/style/styleutil.o: src/style/styleutil.cpp.o

.PHONY : src/style/styleutil.o

# target to build an object file
src/style/styleutil.cpp.o:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/style/styleutil.cpp.o
.PHONY : src/style/styleutil.cpp.o

src/style/styleutil.i: src/style/styleutil.cpp.i

.PHONY : src/style/styleutil.i

# target to preprocess a source file
src/style/styleutil.cpp.i:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/style/styleutil.cpp.i
.PHONY : src/style/styleutil.cpp.i

src/style/styleutil.s: src/style/styleutil.cpp.s

.PHONY : src/style/styleutil.s

# target to generate assembly for a file
src/style/styleutil.cpp.s:
	$(MAKE) -f CMakeFiles/BlockEditor.dir/build.make CMakeFiles/BlockEditor.dir/src/style/styleutil.cpp.s
.PHONY : src/style/styleutil.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... edit_cache"
	@echo "... clean_cotire"
	@echo "... all_unity"
	@echo "... install/local"
	@echo "... BlockEditor_unity"
	@echo "... BlockEditor"
	@echo "... rebuild_cache"
	@echo "... BlockEditor_pch"
	@echo "... install_unity"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... all_pch"
	@echo "... BlockEditor_automoc"
	@echo "... BlockEditor_unity_automoc"
	@echo "... BlockEditor_automoc.o"
	@echo "... BlockEditor_automoc.i"
	@echo "... BlockEditor_automoc.s"
	@echo "... BlockEditor_unity_automoc.o"
	@echo "... BlockEditor_unity_automoc.i"
	@echo "... BlockEditor_unity_automoc.s"
	@echo "... cotire/BlockEditor_CXX_unity_0_13.o"
	@echo "... cotire/BlockEditor_CXX_unity_0_13.i"
	@echo "... cotire/BlockEditor_CXX_unity_0_13.s"
	@echo "... cotire/BlockEditor_CXX_unity_14_26.o"
	@echo "... cotire/BlockEditor_CXX_unity_14_26.i"
	@echo "... cotire/BlockEditor_CXX_unity_14_26.s"
	@echo "... src/highlighter.o"
	@echo "... src/highlighter.i"
	@echo "... src/highlighter.s"
	@echo "... src/item/abstractelement.o"
	@echo "... src/item/abstractelement.i"
	@echo "... src/item/abstractelement.s"
	@echo "... src/item/blankItem.o"
	@echo "... src/item/blankItem.i"
	@echo "... src/item/blankItem.s"
	@echo "... src/item/item.o"
	@echo "... src/item/item.i"
	@echo "... src/item/item.s"
	@echo "... src/item/layout.o"
	@echo "... src/item/layout.i"
	@echo "... src/item/layout.s"
	@echo "... src/item/textitem.o"
	@echo "... src/item/textitem.i"
	@echo "... src/item/textitem.s"
	@echo "... src/lineeditor.o"
	@echo "... src/lineeditor.i"
	@echo "... src/lineeditor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainview.o"
	@echo "... src/mainview.i"
	@echo "... src/mainview.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/minimapview.o"
	@echo "... src/minimapview.i"
	@echo "... src/minimapview.s"
	@echo "... src/scene/blockscene.o"
	@echo "... src/scene/blockscene.i"
	@echo "... src/scene/blockscene.s"
	@echo "... src/scene/command/changemarkedcommand.o"
	@echo "... src/scene/command/changemarkedcommand.i"
	@echo "... src/scene/command/changemarkedcommand.s"
	@echo "... src/scene/command/command.o"
	@echo "... src/scene/command/command.i"
	@echo "... src/scene/command/command.s"
	@echo "... src/scene/command/cursormovecommand.o"
	@echo "... src/scene/command/cursormovecommand.i"
	@echo "... src/scene/command/cursormovecommand.s"
	@echo "... src/scene/command/dragelemententercommand.o"
	@echo "... src/scene/command/dragelemententercommand.i"
	@echo "... src/scene/command/dragelemententercommand.s"
	@echo "... src/scene/command/dragelementleavecommand.o"
	@echo "... src/scene/command/dragelementleavecommand.i"
	@echo "... src/scene/command/dragelementleavecommand.s"
	@echo "... src/scene/command/dropelementcommand.o"
	@echo "... src/scene/command/dropelementcommand.i"
	@echo "... src/scene/command/dropelementcommand.s"
	@echo "... src/scene/command/moveelementcommand.o"
	@echo "... src/scene/command/moveelementcommand.i"
	@echo "... src/scene/command/moveelementcommand.s"
	@echo "... src/scene/command/selectitemcommand.o"
	@echo "... src/scene/command/selectitemcommand.i"
	@echo "... src/scene/command/selectitemcommand.s"
	@echo "... src/scene/linenumbers.o"
	@echo "... src/scene/linenumbers.i"
	@echo "... src/scene/linenumbers.s"
	@echo "... src/scene/mimedata.o"
	@echo "... src/scene/mimedata.i"
	@echo "... src/scene/mimedata.s"
	@echo "... src/scene/parser.o"
	@echo "... src/scene/parser.i"
	@echo "... src/scene/parser.s"
	@echo "... src/scene/sceneeventobserver.o"
	@echo "... src/scene/sceneeventobserver.i"
	@echo "... src/scene/sceneeventobserver.s"
	@echo "... src/scene/scenestate.o"
	@echo "... src/scene/scenestate.i"
	@echo "... src/scene/scenestate.s"
	@echo "... src/style/style.o"
	@echo "... src/style/style.i"
	@echo "... src/style/style.s"
	@echo "... src/style/styleutil.o"
	@echo "... src/style/styleutil.i"
	@echo "... src/style/styleutil.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

